Experiment_name: Skeleton_anonymization_resnet_test

# feeder
feeder: feeders.feeder_anonymization.Feeder
test_feeder_args:
  debug: True
  data_path: ./data/ntu/xview/val_data_joint.npy #/data_seoul/saemi/Understanding-the-Robustness-of-Skeleton-based-Action-Recognition-under-Adversarial-Attack/code/ad_motions.npy
  privacy_label_path:  ./data/ntu/xview/val_label_privacy.pkl
  action_label_path: ./data/ntu/xview/val_label.pkl

# model
anonymizer_model: model.anonymization_res.Anonymizer
model_args:
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

action_model: model.shift_gcn.Model
action_model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

privacy_model: model.shift_gcn.Model
privacy_model_args:
  num_class: 40
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'


phase: 'test'
device: [0,1,2,3]
test_batch_size: 64
nesterov: True

test_action:
  batch_size: 64

test_privacy:
  batch_size: 64

pretrained_action: save_models/ntu_ShiftGCN_joint_xview.pt
pretrained_privacy: save_models/ntu_experiment.pt
pretrained_privacy_test: save_models/ntu_pretrained_0.pt

wandb: "project_name"
dataset: "user"

weights:  save_models/pretrained_resnet.pt